### ISSUE TITLE
Compile Error with Docker Installation

### ISSUE THREAD

**Issue by th3lolipop** [azerothcore/mod-boss-announcer#5]
**OS**: Ubuntu 18.04.4 LTS
**Installation**: Docker Installation

**ERROR MESSAGE**

`[ 16%] Built target authserver
[ 37%] Built target game
Scanning dependencies of target scripts
[ 37%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/GenLoader.cpp.o
[ 37%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-boss-announcer/src/mod_boss_announcer.cpp.o
/azerothcore/modules/mod-boss-announcer/src/mod_boss_announcer.cpp:77:43: fatal error: no member named 'IsHealerTalentSpec' in 'Player'
                    if (itr->GetSource()->IsHealerTalentSpec())
                        ~~~~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-boss-announcer/src/mod_boss_announcer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/server/scripts/CMakeFiles/scripts.dir/build.make:14052: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-boss-announcer/src/mod_boss_announcer.cpp.o' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
CMakeFiles/Makefile2:1347: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

Thanks

**Comment by FrancescoBorzi** [comment]
@Helias

**Comment by Helias** [comment]
Update this module to last version, yesterday I fixed all compiling errors of all modules.

This error should be fixed by this https://github.com/azerothcore/mod-boss-announcer/commit/bfd36128268cdf3b9509926c30002efeee5e9fb0

**Comment by th3lolipop** [comment]
Yes bro @Helias. I updated this module to the latest version,but unfortunately failed like that :/

[![asciicast](https://asciinema.org/a/321690.svg)](https://asciinema.org/a/321690)

**Comment by Helias** [comment]
this is strange, need to investigate a bit, in my local server it works

**Comment by Helias** [comment]
The bug is generated by https://github.com/azerothcore/azerothcore-wotlk/commit/2514f8fc9a3b8f24b89ba5ef402bec3f8f36fee0#diff-3a912d08e1fdcfa7a92a0bdd3a5883c6L1732

I am fixing it replacing `IsHealerTalentSpec` with `HasHealSpec`
